### ISSUE TITLE
Timestamp for 'password reset sent at' or for 'password reset expires at'?

### ISSUE THREAD

**Issue by jdickey** [jdickey/crypt_ident#17]
Presently, we require the User Entity and the schema underlying the User Repository to have an attribute or field, respectively, named `password_reset_sent_at`. This was copied from the API for [another authentication Gem](https://github.com/sebastjan-hribar/tachiban/) that makes more explicit assumptions about how it's being used, e.g., in sending email messages, than our library does. Given how we're now defining `#generate_reset_token` as being that specific and not doing anything else, this name no longer conveys accurate information, since the code that adds that timestamp to a User has no *direct* role in sending an email or any other form of user communication.

Hence, renaming the field as `password_reset_expires_at` makes more sense. It also makes it much simpler to determine whether a Password Reset request has actually Expired, since no processing beyond comparing the current time to the timestamp need be done; the policy is applied on the front rather than back end of that flow.

This would continue to make use of the configuration-specified `:reset_expiry` value in computing that value.

Finally, that should probably be a GMT/UTC timestamp rather than a server-local-time timestamp (as Ruby's `time.now` returns by default).

**Comment by mitpaladin** [comment]
agreed, `password_reset_expires_at` would be better as it is explicit
